import MeaningGraph
import SemanticHash
import TrustAnnotations
import TrustExtractor.Util
import TrustExtractor.Hash
import TrustExtractor.Source
import TrustExtractor.Packages

/-!
# Extraction: a compiled project to an S2 dataset

The dataset (spec `ltb-dataset/0`, see LeanTrustBuilders/specs) is a directory:

* `meta.json`: what produced the dataset, from what, and which edge files and facets it holds;
* `decls.jsonl`: one line per node — identity, kind, and the three hashes of the declaration key;
* `edges/<notion>.bin`: little-endian `int32` pairs `(source id, target id)`, one file per notion of
  dependency;
* `facets/<name>.jsonl`: everything else about declarations, one file per facet, keyed by name.

**Nodes** are the project's own declarations (MeaningGraph's `shouldExpose`: written by a person,
not generated by the compiler) and the upstream constants that their statements and data mention.
Upstream nodes have no outgoing edges: they are where a closure leaves the project.

**Notions of dependency** (MeaningGraph's `DeclDeps`):

* `statement`: the constants the declaration's type mentions (`typeDeps`);
* `meaning`: what the declaration means — the statement for a proof, the statement and the data of
  the value for a definition, with the proofs embedded in the value skipped (`typeDeps` or
  `dataDeps`). This is the closure coverage is computed over;
* `term`: the type and the whole value, proofs included (`deps`). Restricted to edges whose target
  is a node, so lemmas used only in proofs of upstream packages are not listed.
-/

namespace TrustExtractor

open Lean

/-- The dataset specification this extractor writes. -/
def datasetSpec : String := "ltb-dataset/0"

/-- This extractor's version. -/
def extractorVersion : String := "0.1.0"

/-- The semantic_hash revision this extractor is built against. Must match `lakefile.toml`;
`trust-extract version` prints it and CI checks the two agree. -/
def semanticHashRevision : String := "0496f6d7b650cb03c9ffc61089ffd400dfd98564"

/-- What to extract, and where to. -/
structure Config where
  /-- The project's root module prefix, e.g. `TauCeti`. -/
  root : Name
  /-- Directories to look for the project's sources in. -/
  srcDirs : Array System.FilePath := #["."]
  /-- Modules to import. Empty means every module under `srcDirs` with the `root` prefix. -/
  modules : Array Name := #[]
  /-- The directory the dataset is written to. -/
  out : System.FilePath := "dataset"
  /-- The project's repository, e.g. `TauCetiProject/TauCeti`, recorded in `meta.json`. -/
  repo : String := ""
  /-- The project's commit. Empty means `git rev-parse HEAD` in the working directory. -/
  commit : String := ""
  /-- The package label of the project. Empty means the root prefix. -/
  project : String := ""
  /-- Whether to compute the `axioms` facet. -/
  axioms : Bool := true

/-- The kind of a declaration, as recorded in `decls.jsonl`. -/
def kindOf (env : Environment) (name : Name) (info : ConstantInfo) : String :=
  if Meta.isInstanceCore env name then "instance"
  else if isClass env name then "class"
  else match info with
    | .thmInfo _ => "theorem"
    | .opaqueInfo _ => "opaque"
    | .axiomInfo _ => "axiom"
    | .inductInfo _ => if isStructure env name then "structure" else "inductive"
    | .defnInfo _ => "definition"
    | .ctorInfo _ => "constructor"
    | .recInfo _ => "recursor"
    | .quotInfo _ => "quotient"

/-- Every module under `dir` (a directory for the module prefix `pref`). -/
partial def discoverUnder (dir : System.FilePath) (pref : Name) : IO (Array Name) := do
  let mut acc := #[]
  for entry in ← dir.readDir do
    if ← entry.path.isDir then
      acc := acc ++ (← discoverUnder entry.path (pref.str entry.fileName))
    else if entry.fileName.endsWith ".lean" then
      acc := acc.push (pref.str (entry.fileName.dropEnd 5).toString)
  return acc

/-- The project's modules: the root module if it has a file, and every module under the root's
directory, sorted so that the dataset does not depend on the order the file system lists them. -/
def discoverModules (srcDirs : Array System.FilePath) (root : Name) : IO (Array Name) := do
  let mut mods : Array Name := #[]
  for dir in srcDirs do
    if ← (dir / modulePath root).pathExists then mods := mods.push root
    let rootDir := dir / System.mkFilePath (root.components.map toString)
    if ← rootDir.isDir then mods := mods ++ (← discoverUnder rootDir root)
  return (mods.qsort (·.toString < ·.toString)).toList.eraseDups.toArray

/-- One node of the dataset. -/
structure Node where
  name : Name
  info : ConstantInfo
  project : Bool
deriving Inhabited

/-- A description of one edge file or facet in `meta.json`. -/
def fileEntry (name file schema : String) (count : Nat) (description : String) : Json :=
  Json.mkObj [("name", toJson name), ("file", toJson file), ("schema", toJson schema),
    ("count", toJson count), ("description", toJson description)]

/-- Extracts the dataset. The caller must have run `enableInitializersExecution`, so that the
imported modules' extensions (among them `TrustAnnotations`') are registered and filled. -/
def extract (cfg : Config) : IO Unit := do
  let t0 ← IO.monoMsNow
  initSearchPath (← findSysroot)
  let mods ← if cfg.modules.isEmpty then discoverModules cfg.srcDirs cfg.root else pure cfg.modules
  if mods.isEmpty then
    throw <| IO.userError s!"no modules found under the prefix `{cfg.root}` in {cfg.srcDirs}"
  let project := if cfg.project.isEmpty then cfg.root.toString else cfg.project
  let commit ← if cfg.commit.isEmpty then
      pure ((← commandOutput? "git" #["rev-parse", "HEAD"]).getD "")
    else pure cfg.commit
  let dirty := !((← commandOutput? "git" #["status", "--porcelain"]).getD "").isEmpty
  -- The project's own pin: `Lean.versionString` drops the release-candidate suffix.
  let toolchain ← do
    let f : System.FilePath := "lean-toolchain"
    if ← f.pathExists then pure (← IO.FS.readFile f).trimAscii.toString
    else pure s!"leanprover/lean4:v{Lean.versionString}"

  progress t0 s!"importing {mods.size} modules"
  let env ← importModules (mods.map ({ module := · })) {} (loadExts := true)
  progress t0 "imported"

  -- Dependencies.
  let ctx := MeaningGraph.Context.of env cfg.root
  let ctx ← runMetaM env ctx.withDataValueConsts
  let deps := ctx.allDeclDeps
  progress t0 s!"dependencies of {deps.size} project declarations"

  -- Nodes: the project's declarations, then the upstream constants their statements and data
  -- mention, sorted by name.
  let projectNames : Std.HashSet Name := deps.foldl (fun s (n, _) => s.insert n) {}
  let mut upstream : Std.HashSet Name := {}
  for (_, d) in deps do
    for dep in d.typeDeps ++ d.dataDeps do
      if !projectNames.contains dep && env.contains dep then
        upstream := upstream.insert dep
  let upstreamSorted := upstream.toArray.qsort (·.toString < ·.toString)
  let mut nodes : Array Node := #[]
  for (n, _) in deps do
    if let some info := env.find? n then nodes := nodes.push { name := n, info, project := true }
  for n in upstreamSorted do
    if let some info := env.find? n then nodes := nodes.push { name := n, info, project := false }
  let ids : Std.HashMap Name Nat :=
    (Array.range nodes.size).foldl (fun m i => m.insert nodes[i]!.name i) {}
  progress t0 s!"{projectNames.size} project nodes, {upstreamSorted.size} upstream nodes"

  -- Whether each node is a proof.
  let isProp ← runMetaM env do
    nodes.mapM fun node => do
      if node.info matches .thmInfo _ then return true
      try Meta.isProp node.info.type catch _ => return false

  -- Hashes.
  let hashes ← SemanticHash.Hashing.runBoth env
  progress t0 "semantic hashes"
  let locals ← nodes.mapM fun node => (localHash env node.info : IO UInt64)

  -- Packages.
  let search ← labelledSearchPath project
  let pkgCache ← IO.mkRef ({} : Std.HashMap Name String)
  let moduleOf (n : Name) : Name :=
    match env.getModuleIdxFor? n with
    | some idx => env.header.moduleNames[idx.toNat]!
    | none => .anonymous

  IO.FS.createDirAll (cfg.out / "edges")
  IO.FS.createDirAll (cfg.out / "facets")

  -- decls.jsonl
  let mut declLines : Array Json := #[]
  for h : i in [0:nodes.size] do
    let node := nodes[i]
    let mod := moduleOf node.name
    let pkg ← packageOf search pkgCache mod
    let hs := Json.mkObj <|
      (match hashes.proofIrrelHashes.get? node.name with
        | some h => [("meaning", toJson (hex16 h))] | none => []) ++
      (match hashes.fullHashes.get? node.name with
        | some h => [("content", toJson (hex16 h))] | none => []) ++
      [("local", toJson (hex16 locals[i]!))]
    declLines := declLines.push <| Json.mkObj [
      ("id", toJson i), ("name", toJson node.name.toString), ("module", toJson mod.toString),
      ("package", toJson pkg), ("scope", toJson (if node.project then "project" else "upstream")),
      ("kind", toJson (kindOf env node.name node.info)), ("isProp", toJson isProp[i]!),
      ("hashes", hs)]
  writeJsonl (cfg.out / "decls.jsonl") declLines
  progress t0 "wrote decls.jsonl"

  -- Edges.
  let notions : Array (String × String × (Nat → MeaningGraph.DeclDeps → Array Name)) := #[
    ("statement", "the constants the declaration's type mentions", fun _ d => d.typeDeps),
    ("meaning", "what the declaration means: its statement for a proof; its statement and the \
      data of its value, proofs skipped, for a definition", fun i d =>
        if isProp[i]! then d.typeDeps else d.dataDeps),
    ("term", "the type and the whole value, proofs included, restricted to targets that are nodes",
      fun _ d => d.deps)]
  let mut edgeEntries : Array Json := #[]
  for (notion, description, select) in notions do
    let mut buf : ByteArray := .empty
    let mut count := 0
    for h : i in [0:deps.size] do
      let (n, d) := deps[i]
      let some src := ids.get? n | continue
      for dep in select src d do
        if let some tgt := ids.get? dep then
          buf := pushI32LE (pushI32LE buf src) tgt
          count := count + 1
    IO.FS.writeBinFile (cfg.out / "edges" / s!"{notion}.bin") buf
    edgeEntries := edgeEntries.push <| Json.mkObj [
      ("name", toJson notion), ("file", toJson s!"edges/{notion}.bin"),
      ("format", toJson "i32le-pairs"), ("count", toJson count),
      ("description", toJson description)]
  progress t0 "wrote edges"

  -- Facets.
  let mut facetEntries : Array Json := #[]
  let projectNodes := nodes.filter (·.project)

  -- docstring
  let mut docLines : Array Json := #[]
  for node in projectNodes do
    if let some doc ← findDocString? env node.name then
      docLines := docLines.push <| Json.mkObj [("decl", toJson node.name.toString), ("text", toJson doc)]
  writeJsonl (cfg.out / "facets" / "docstring.jsonl") docLines
  facetEntries := facetEntries.push <| fileEntry "docstring" "facets/docstring.jsonl" "docstring/1"
    docLines.size "the declaration's docstring, verbatim"

  -- source
  let ranges ← runCoreM env do
    projectNodes.mapM fun node => return (node.name, ← findDeclarationRanges? node.name)
  let texts ← IO.mkRef ({} : Std.HashMap Name (Option (String × System.FilePath)))
  let cwd ← IO.currentDir
  let mut srcLines : Array Json := #[]
  for (name, range?) in ranges do
    let some range := range? | continue
    let mod := moduleOf name
    let cached := (← texts.get).get? mod
    let file? ← match cached with
      | some f => pure f
      | none => do
        let f ← match ← findSource? cfg.srcDirs mod with
          | some p => pure (some ((← IO.FS.readFile p), p))
          | none => pure none
        texts.modify (·.insert mod f)
        pure f
    let some (text, path) := file? | continue
    let fileMap := text.toFileMap
    let pos := fileMap.ofPosition range.range.pos
    let relPath :=
      let s := path.toString
      let c := cwd.toString ++ "/"
      if s.startsWith c then (s.drop c.length).toString
      else if s.startsWith "./" then (s.drop 2).toString else s
    let loc : SourceLoc := {
      path := relPath
      startLine := range.range.pos.line, startCol := range.range.charUtf16
      endLine := range.range.endPos.line, endCol := range.range.endCharUtf16
      keyword := keywordAt text pos }
    srcLines := srcLines.push (loc.asJson name)
  writeJsonl (cfg.out / "facets" / "source.jsonl") srcLines
  facetEntries := facetEntries.push <| fileEntry "source" "facets/source.jsonl" "source/1"
    srcLines.size "where the declaration is written: path relative to the project root, start and \
    end as [line, column] (lines 1-based, columns in UTF-16 code units, 0-based), and the keyword \
    it is written with"
  progress t0 "wrote docstring and source facets"

  -- axioms
  if cfg.axioms then
    let axioms ← runCoreM env do
      projectNodes.mapM fun node => return (node.name, ← collectAxioms node.name)
    let axLines := axioms.map fun (name, axs) =>
      let sorted := axs.qsort (·.toString < ·.toString)
      Json.mkObj [("decl", toJson name.toString),
        ("axioms", toJson (sorted.map (·.toString))),
        ("sorry", toJson (axs.contains ``sorryAx))]
    writeJsonl (cfg.out / "facets" / "axioms.jsonl") axLines
    facetEntries := facetEntries.push <| fileEntry "axioms" "facets/axioms.jsonl" "axioms/1"
      axLines.size "the axioms the declaration depends on, transitively, and whether `sorryAx` \
      is among them"
    progress t0 "wrote axioms facet"

  -- annotations, one facet per attribute
  let entries := (TrustAnnotations.entries env).filter (ids.contains ·.decl)
  let attrs := (entries.map (·.attr)).toList.eraseDups.toArray.qsort (·.toString < ·.toString)
  for attr in attrs do
    let lines := (entries.filter (·.attr == attr)).map fun e =>
      Json.mkObj [("decl", toJson e.decl.toString),
        ("payload", (Json.parse e.payload).toOption.getD (toJson e.payload))]
    let file := s!"facets/annotation.{attr}.jsonl"
    writeJsonl (cfg.out / file) lines
    facetEntries := facetEntries.push <| fileEntry s!"annotation.{attr}" file "annotation/1"
      lines.size s!"`@[{attr}]` annotations recorded in the TrustAnnotations extension"

  -- meta.json
  let metaJson := Json.mkObj [
    ("spec", toJson datasetSpec),
    ("producer", Json.mkObj [("name", toJson "trust-extract"), ("version", toJson extractorVersion)]),
    ("library", Json.mkObj [("root", toJson cfg.root.toString), ("package", toJson project),
      ("repo", toJson cfg.repo), ("commit", toJson commit), ("dirty", toJson dirty),
      ("modules", toJson mods.size)]),
    ("toolchain", toJson toolchain),
    ("lean", Json.mkObj [("version", toJson Lean.versionString), ("githash", toJson Lean.githash)]),
    ("hasher", Json.mkObj [("name", toJson "semantic_hash"),
      ("revision", toJson semanticHashRevision), ("meaning", toJson "proof-irrelevant"),
      ("content", toJson "proof-relevant"), ("local", toJson localHasherName)]),
    ("counts", Json.mkObj [("nodes", toJson nodes.size), ("project", toJson projectNodes.size),
      ("upstream", toJson (nodes.size - projectNodes.size))]),
    ("edges", toJson edgeEntries),
    ("facets", toJson facetEntries)]
  IO.FS.writeFile (cfg.out / "meta.json") (metaJson.pretty ++ "\n")
  progress t0 s!"wrote {cfg.out}"

end TrustExtractor
