import MeaningGraph
import SemanticHash
import TrustAnnotations
import TrustExtractor.Util
import TrustExtractor.Hash
import TrustExtractor.Source
import TrustExtractor.Packages

/-!
# Extraction: a compiled project to an S2 dataset

The dataset (spec `ltb-dataset/0`, see LeanTrustBuilders/specs) is a directory:

* `meta.json`: what produced the dataset, from what, and which edge files and facets it holds;
* `decls.jsonl`: one line per node — identity, kind, and the three hashes of the declaration key;
* `edges/<notion>.bin`: little-endian `int32` pairs `(source id, target id)`, one file per notion of
  dependency;
* `facets/<name>.jsonl`: everything else about declarations, one file per facet, keyed by name.

**Nodes** are the project's own declarations (MeaningGraph's `shouldExpose`: written by a person,
not generated by the compiler) and the upstream constants that their statements and data mention.
Upstream nodes have no outgoing edges: they are where a closure leaves the project.

**Notions of dependency** (MeaningGraph's `DeclDeps`):

* `statement`: the constants the declaration's type mentions (`typeDeps`);
* `meaning`: what the declaration means — the statement for a proof, the statement and the data of
  the value for a definition, with the proofs embedded in the value skipped (`typeDeps` or
  `dataDeps`). This is the closure coverage is computed over;
* `term`: the type and the whole value, proofs included (`deps`), restricted to edges whose target
  is a node.

## Parts

Importing a large project in one process can exceed Linux's limit on memory mappings
(`vm.max_map_count`): every module maps several files. So the work is split into **parts**. A part
imports some of the project's modules (and, through them, whatever they import) and reports, for the
declarations of *those* modules only, their nodes, edges and facets, keyed by name. The dependencies
and hashes of a declaration depend only on what its module can see, so a declaration's data is the
same in every part that could compute it, and merging the parts gives the same dataset as a single
import. Nodes are ordered canonically (project nodes by module name, then by position in the module;
upstream nodes by name), so the dataset does not depend on how the work was split.
-/

namespace TrustExtractor

open Lean

/-- The dataset specification this extractor writes. -/
def datasetSpec : String := "ltb-dataset/0"

/-- This extractor's version. -/
def extractorVersion : String := "0.3.0"

/-- The semantic_hash revision this extractor is built against. Must match `lakefile.toml`;
`scripts/check-pins.py` checks the two agree. -/
def semanticHashRevision : String := "0496f6d7b650cb03c9ffc61089ffd400dfd98564"

/-- What to extract, and where to. -/
structure Config where
  /-- The project's root module prefix, e.g. `TauCeti`. -/
  root : Name
  /-- Directories to look for the project's sources in. -/
  srcDirs : Array System.FilePath := #["."]
  /-- Modules to import. Empty means every module under `srcDirs` with the `root` prefix. -/
  modules : Array Name := #[]
  /-- The directory the dataset is written to. -/
  out : System.FilePath := "dataset"
  /-- The project's repository, e.g. `TauCetiProject/TauCeti`, recorded in `meta.json`. -/
  repo : String := ""
  /-- The project's commit. Empty means `git rev-parse HEAD` in the working directory. -/
  commit : String := ""
  /-- The package label of the project. Empty means the root prefix. -/
  project : String := ""
  /-- Whether to compute the `axioms` facet. -/
  axioms : Bool := true
  /-- The number of parts to start with; a part that runs out of memory mappings is split. -/
  parts : Nat := 1
  /-- How many parts to run at once. -/
  jobs : Nat := 1
  /-- Whether to compute the `term` notion, which walks every proof term. -/
  term : Bool := true
  /-- Modules not to extract, typically because they do not build at this commit. The modules
  that import them, directly or not, are not extracted either. -/
  skip : Array Name := #[]

/-- The kind of a declaration, as recorded in `decls.jsonl`. -/
def kindOf (env : Environment) (name : Name) (info : ConstantInfo) : String :=
  if Meta.isInstanceCore env name then "instance"
  else if isClass env name then "class"
  else match info with
    | .thmInfo _ => "theorem"
    | .opaqueInfo _ => "opaque"
    | .axiomInfo _ => "axiom"
    | .inductInfo _ => if isStructure env name then "structure" else "inductive"
    | .defnInfo _ => "definition"
    | .ctorInfo _ => "constructor"
    | .recInfo _ => "recursor"
    | .quotInfo _ => "quotient"

/-- Every module under `dir` (a directory for the module prefix `pref`). -/
partial def discoverUnder (dir : System.FilePath) (pref : Name) : IO (Array Name) := do
  let mut acc := #[]
  for entry in ← dir.readDir do
    if ← entry.path.isDir then
      acc := acc ++ (← discoverUnder entry.path (pref.str entry.fileName))
    else if entry.fileName.endsWith ".lean" then
      acc := acc.push (pref.str (entry.fileName.dropEnd 5).toString)
  return acc

/-- The project's modules: the root module if it has a file, and every module under the root's
directory, sorted so that the dataset does not depend on the order the file system lists them. -/
def discoverModules (srcDirs : Array System.FilePath) (root : Name) : IO (Array Name) := do
  let mut mods : Array Name := #[]
  for dir in srcDirs do
    if ← (dir / modulePath root).pathExists then mods := mods.push root
    let rootDir := dir / System.mkFilePath (root.components.map toString)
    if ← rootDir.isDir then mods := mods ++ (← discoverUnder rootDir root)
  return (mods.qsort (·.toString < ·.toString)).toList.eraseDups.toArray

/-- The modules among `mods` that are in `skip` or import one of them, directly or not, sorted.
A module that does not build takes down every module importing it, and Lake's report of failed
targets names only the modules that failed, not those it did not try. Imports are read from the
source headers, without importing anything. -/
def withImporters (srcDirs : Array System.FilePath) (mods : Array Name) (skip : Array Name) :
    IO (Array Name) := do
  let mut importers : Std.HashMap Name (Array Name) := {}
  for m in mods do
    let some path ← findSource? srcDirs m | continue
    let header ← parseImports' (← IO.FS.readFile path) path.toString
    for i in header.imports do
      importers := importers.insert i.module ((importers.getD i.module #[]).push m)
  let known : Std.HashSet Name := mods.foldl (·.insert ·) {}
  let mut out : Std.HashSet Name := {}
  let mut todo := skip
  while !todo.isEmpty do
    let m := todo.back!
    todo := todo.pop
    if out.contains m then continue
    out := out.insert m
    todo := todo ++ importers.getD m #[]
  return out.toArray.filter known.contains |>.qsort (·.toString < ·.toString)

/-! ## One part -/

/-- A node, as a part reports it. -/
structure NodeInfo where
  name : Name
  module : Name
  /-- Position of the declaration in its module's constant table: the canonical order of project
  nodes within a module. -/
  pos : Nat
  package : String
  project : Bool
  kind : String
  isProp : Bool
  meaning : Option String
  content : Option String
  localHash : String
deriving Inhabited

def NodeInfo.asJson (n : NodeInfo) : Json :=
  Json.mkObj [("name", toJson n.name.toString), ("module", toJson n.module.toString),
    ("pos", toJson n.pos), ("package", toJson n.package), ("project", toJson n.project),
    ("kind", toJson n.kind), ("isProp", toJson n.isProp), ("meaning", toJson n.meaning),
    ("content", toJson n.content), ("local", toJson n.localHash)]

def NodeInfo.ofJson (j : Json) : Except String NodeInfo := do
  return { name := (← j.getObjValAs? String "name").toName
           module := (← j.getObjValAs? String "module").toName
           pos := ← j.getObjValAs? Nat "pos", package := ← j.getObjValAs? String "package"
           project := ← j.getObjValAs? Bool "project", kind := ← j.getObjValAs? String "kind"
           isProp := ← j.getObjValAs? Bool "isProp"
           meaning := (j.getObjValAs? String "meaning").toOption
           content := (j.getObjValAs? String "content").toOption
           localHash := ← j.getObjValAs? String "local" }

/-- The notions of dependency, in the order their edge files are written. -/
def notionNames : Array String := #["statement", "meaning", "term"]

def notionDescription : String → String
  | "statement" => "the constants the declaration's type mentions"
  | "meaning" => "what the declaration means: its statement for a proof; its statement and the \
      data of its value, proofs skipped, for a definition"
  | "term" => "the type and the whole value, proofs included, restricted to targets that are nodes"
  | _ => ""

/-- A facet's description in `meta.json`. -/
structure FacetInfo where
  name : String
  schema : String
  description : String
deriving Inhabited

/-- A facet description. -/
def facetInfo (name schema description : String) : FacetInfo := { name, schema, description }

/-- What one part reports. Everything is keyed by name, so parts can be merged. -/
structure Part where
  /-- Nodes: the project declarations of the requested modules, and every constant their
  statement and data edges point to. -/
  nodes : Array NodeInfo
  /-- The project declarations this part is authoritative for. -/
  owned : Array Name
  /-- For each owned declaration, its targets under each notion (in `notionNames` order). -/
  edges : Array (Name × Array (Array Name))
  /-- Facet rows, by facet name. -/
  facets : Array (FacetInfo × Array Json)
  /-- The number of modules the part imported. -/
  imported : Nat
deriving Inhabited

def Part.asJson (p : Part) : Json :=
  Json.mkObj [
    ("nodes", Json.arr (p.nodes.map NodeInfo.asJson)),
    ("owned", toJson (p.owned.map toString)),
    ("edges", Json.arr (p.edges.map fun (n, ts) =>
      Json.mkObj [("decl", toJson n.toString),
        ("targets", toJson (ts.map (·.map toString)))])),
    ("facets", Json.arr (p.facets.map fun (f, rows) =>
      Json.mkObj [("name", toJson f.name), ("schema", toJson f.schema),
        ("description", toJson f.description), ("rows", Json.arr rows)])),
    ("imported", toJson p.imported)]

def Part.ofJson (j : Json) : Except String Part := do
  let nodes ← (← j.getObjValAs? (Array Json) "nodes").mapM NodeInfo.ofJson
  let owned := (← j.getObjValAs? (Array String) "owned").map (·.toName)
  let edges ← (← j.getObjValAs? (Array Json) "edges").mapM fun e => do
    let ts ← e.getObjValAs? (Array (Array String)) "targets"
    return ((← e.getObjValAs? String "decl").toName, ts.map (·.map (·.toName)))
  let facets ← (← j.getObjValAs? (Array Json) "facets").mapM fun f => do
    return ({ name := ← f.getObjValAs? String "name", schema := ← f.getObjValAs? String "schema"
              description := ← f.getObjValAs? String "description" },
            ← f.getObjValAs? (Array Json) "rows")
  return { nodes, owned, edges, facets, imported := ← j.getObjValAs? Nat "imported" }

/-- Collects one part: imports `mods` and reports on the project declarations of those modules.
The caller must have run `enableInitializersExecution`, so that the imported modules' extensions
(among them `TrustAnnotations`') are registered and filled. -/
def collectPart (cfg : Config) (mods : Array Name) (project : String) (t0 : Nat) : IO Part := do
  initSearchPath (← findSysroot)
  progress t0 s!"importing {mods.size} modules"
  let env ← importModules (mods.map ({ module := · })) {} (loadExts := true)
  progress t0 s!"imported {env.header.moduleNames.size} modules"
  let requested : Std.HashSet Name := mods.foldl (·.insert ·) {}

  let moduleOf (n : Name) : Name := (MeaningGraph.moduleNameOf env n).getD .anonymous

  -- The project declarations of the requested modules, in module order.
  let ctx := MeaningGraph.Context.of env cfg.root
  progress t0 s!"dependency tables: {ctx.constants.size} project constants, {ctx.exposed.size} exposed"
  let mut positions : Std.HashMap Name Nat := {}
  let mut ownedInfos : Array (Name × ConstantInfo) := #[]
  for (name, mod, info) in ctx.constants do
    if requested.contains mod then
      positions := positions.insert name positions.size
      if ctx.exposed.contains name then ownedInfos := ownedInfos.push (name, info)
  let owned := ownedInfos.map (·.1)
  let ownedProp ← runMetaM env do
    ownedInfos.mapM fun (_, info) => do
      if info matches .thmInfo _ then return true
      try Meta.isProp info.type catch _ => return false

  -- The data of the owned definitions' values, proofs skipped.
  let ctx ← runMetaM env (ctx.withDataValueConsts (only := some (owned.foldl (·.insert ·) {})))
  progress t0 s!"data values of {ctx.dataValueConsts.size} definitions"

  -- Dependencies under each notion, from MeaningGraph's lists: `statement` is `typeDeps`; `meaning`
  -- is `typeDeps` for a proof, whose meaning is its statement, and `dataDeps` otherwise; `term` is
  -- `deps`. A proof's value, the proof term, is walked only for `term`.
  let proofs := (ownedInfos.zip ownedProp).filterMap fun (ni, p) => if p then some ni else none
  let others := (ownedInfos.zip ownedProp).filterMap fun (ni, p) => if p then none else some ni
  let computed := ctx.depsOf proofs { deps := cfg.term, dataDeps := false } ++
    ctx.depsOf others { deps := cfg.term }
  let byName : Std.HashMap Name MeaningGraph.DeclDeps := computed.foldl (fun m (n, d) => m.insert n d) {}
  let deps : Array (Name × Array (Array Name)) := (ownedInfos.zip ownedProp).map fun ((n, _), p) =>
    let d := byName.getD n default
    (n, #[d.typeDeps, if p then d.typeDeps else d.dataDeps, d.deps])
  progress t0 s!"dependencies of {deps.size} project declarations"

  -- Nodes: the owned declarations, and the targets of their statement and meaning edges.
  let ownedSet : Std.HashSet Name := owned.foldl (·.insert ·) {}
  let mut others : Std.HashSet Name := {}
  for (_, d) in deps do
    for dep in d[0]! ++ d[1]! do
      if !ownedSet.contains dep && env.contains dep then others := others.insert dep
  let otherInfos := others.toArray.filterMap fun n => (env.find? n).map (n, ·)
  let otherProp ← runMetaM env do
    otherInfos.mapM fun (_, info) => do
      if info matches .thmInfo _ then return true
      try Meta.isProp info.type catch _ => return false
  let infos := ownedInfos ++ otherInfos
  let isProp := ownedProp ++ otherProp
  let nodeNames := infos.map (·.1)
  let hashes ← SemanticHash.Hashing.runBoth env
  progress t0 "semantic hashes"
  let search ← labelledSearchPath project
  let pkgCache ← IO.mkRef ({} : Std.HashMap Name String)
  let mut nodes : Array NodeInfo := #[]
  for h : i in [0:infos.size] do
    let (name, info) := infos[i]
    let mod := moduleOf name
    nodes := nodes.push {
      name, module := mod, pos := positions.getD name 0
      package := ← packageOf search pkgCache mod
      project := MeaningGraph.isProjectLocalConst env cfg.root name
      kind := kindOf env name info, isProp := isProp[i]!
      meaning := (hashes.proofIrrelHashes.get? name).map hex16
      content := (hashes.fullHashes.get? name).map hex16
      localHash := hex16 (← (localHash env info : IO UInt64)) }

  -- Edges, by name.
  let edges := deps

  -- Facets.
  let mut facets : Array (FacetInfo × Array Json) := #[]
  let mut docRows : Array Json := #[]
  for n in owned do
    if let some doc ← findDocString? env n then
      docRows := docRows.push <| Json.mkObj [("decl", toJson n.toString), ("text", toJson doc)]
  facets := facets.push
    (facetInfo "docstring" "docstring/1" "the declaration's docstring, verbatim", docRows)

  let ranges ← runCoreM env do
    owned.mapM fun n => return (n, ← findDeclarationRanges? n)
  let texts ← IO.mkRef ({} : Std.HashMap Name (Option (String × System.FilePath)))
  let cwd ← IO.currentDir
  let mut srcRows : Array Json := #[]
  for (name, range?) in ranges do
    let some range := range? | continue
    let mod := moduleOf name
    let file? ← match (← texts.get).get? mod with
      | some f => pure f
      | none => do
        let f ← match ← findSource? cfg.srcDirs mod with
          | some p => pure (some ((← IO.FS.readFile p), p))
          | none => pure none
        texts.modify (·.insert mod f)
        pure f
    let some (text, path) := file? | continue
    let pos := text.toFileMap.ofPosition range.range.pos
    let relPath :=
      let s := path.toString
      let c := cwd.toString ++ "/"
      if s.startsWith c then (s.drop c.length).toString
      else if s.startsWith "./" then (s.drop 2).toString else s
    let loc : SourceLoc := {
      path := relPath
      startLine := range.range.pos.line, startCol := range.range.charUtf16
      endLine := range.range.endPos.line, endCol := range.range.endCharUtf16
      keyword := keywordAt text pos }
    srcRows := srcRows.push (loc.asJson name)
  facets := facets.push (facetInfo "source" "source/1" "where the declaration is written: path relative to the project root, start and \
      end as [line, column] (lines 1-based, columns in UTF-16 code units, 0-based), and the \
      keyword it is written with", srcRows)
  progress t0 "docstring and source facets"

  if cfg.axioms then
    let axioms ← runCoreM env do
      owned.mapM fun n => return (n, ← collectAxioms n)
    let rows := axioms.map fun (n, axs) =>
      Json.mkObj [("decl", toJson n.toString),
        ("axioms", toJson ((axs.qsort (·.toString < ·.toString)).map (·.toString))),
        ("sorry", toJson (axs.contains ``sorryAx))]
    facets := facets.push (facetInfo "axioms" "axioms/1" "the axioms the declaration depends on, transitively, and whether `sorryAx` \
        is among them", rows)
    progress t0 "axioms facet"

  -- Annotations on any node. Several parts may report the same one; the merge keeps one copy.
  let nodeSet : Std.HashSet Name := nodeNames.foldl (·.insert ·) {}
  let entries := (TrustAnnotations.entries env).filter (nodeSet.contains ·.decl)
  let attrs := (entries.map (·.attr)).toList.eraseDups.toArray
  for attr in attrs do
    let rows := (entries.filter (·.attr == attr)).map fun e =>
      Json.mkObj [("decl", toJson e.decl.toString),
        ("payload", (Json.parse e.payload).toOption.getD (toJson e.payload))]
    facets := facets.push (facetInfo s!"annotation.{attr}" "annotation/1"
      s!"`@[{attr}]` annotations recorded in the TrustAnnotations extension", rows)

  return { nodes, owned, edges, facets, imported := env.header.moduleNames.size }

/-! ## Merging parts into a dataset -/

/-- Merges parts and writes the dataset. -/
def writeDataset (cfg : Config) (parts : Array Part) (mods : Array Name) (project : String)
    (unavailable : Array Name) (t0 : Nat) : IO Unit := do
  let commit ← if cfg.commit.isEmpty then
      pure ((← commandOutput? "git" #["rev-parse", "HEAD"]).getD "")
    else pure cfg.commit
  let dirty := !((← commandOutput? "git" #["status", "--porcelain"]).getD "").isEmpty
  -- The project's own pin: `Lean.versionString` drops the release-candidate suffix.
  let toolchain ← do
    let f : System.FilePath := "lean-toolchain"
    if ← f.pathExists then pure (← IO.FS.readFile f).trimAscii.toString
    else pure s!"leanprover/lean4:v{Lean.versionString}"

  -- Nodes: owned project nodes from the part that owns them; upstream nodes from any part.
  let mut owner : Std.HashMap Name NodeInfo := {}
  for p in parts do
    let ownedSet : Std.HashSet Name := p.owned.foldl (·.insert ·) {}
    for n in p.nodes do
      if ownedSet.contains n.name then owner := owner.insert n.name n
  let mut others : Std.HashMap Name NodeInfo := {}
  for p in parts do
    for n in p.nodes do
      if !owner.contains n.name && !others.contains n.name && !n.project then
        others := others.insert n.name n
  let projectNodes := owner.toArray.map (·.2) |>.qsort fun a b =>
    a.module.toString < b.module.toString || (a.module == b.module && a.pos < b.pos)
  let upstreamNodes := others.toArray.map (·.2) |>.qsort (·.name.toString < ·.name.toString)
  let nodes := projectNodes ++ upstreamNodes
  let ids : Std.HashMap Name Nat :=
    (Array.range nodes.size).foldl (fun m i => m.insert nodes[i]!.name i) {}
  progress t0 s!"{projectNodes.size} project nodes, {upstreamNodes.size} upstream nodes"

  IO.FS.createDirAll (cfg.out / "edges")
  IO.FS.createDirAll (cfg.out / "facets")

  let declLines := (Array.range nodes.size).map fun i =>
    let n := nodes[i]!
    let hs := Json.mkObj <|
      (match n.meaning with | some h => [("meaning", toJson h)] | none => []) ++
      (match n.content with | some h => [("content", toJson h)] | none => []) ++
      [("local", toJson n.localHash)]
    Json.mkObj [("id", toJson i), ("name", toJson n.name.toString),
      ("module", toJson n.module.toString), ("package", toJson n.package),
      ("scope", toJson (if n.project then "project" else "upstream")), ("kind", toJson n.kind),
      ("isProp", toJson n.isProp), ("hashes", hs)]
  writeJsonl (cfg.out / "decls.jsonl") declLines

  -- Edges, in node order.
  let mut targets : Std.HashMap Name (Array (Array Name)) := {}
  for p in parts do
    for (n, ts) in p.edges do targets := targets.insert n ts
  let mut edgeEntries : Array Json := #[]
  for h : k in [0:notionNames.size] do
    let notion := notionNames[k]
    if notion == "term" && !cfg.term then continue
    let mut buf : ByteArray := .empty
    let mut count := 0
    for n in projectNodes do
      let some src := ids.get? n.name | continue
      let some ts := targets.get? n.name | continue
      for t in ts[k]! do
        if let some tgt := ids.get? t then
          buf := pushI32LE (pushI32LE buf src) tgt
          count := count + 1
    IO.FS.writeBinFile (cfg.out / "edges" / s!"{notion}.bin") buf
    edgeEntries := edgeEntries.push <| Json.mkObj [
      ("name", toJson notion), ("file", toJson s!"edges/{notion}.bin"),
      ("format", toJson "i32le-pairs"), ("count", toJson count),
      ("description", toJson (notionDescription notion))]

  -- Facets: rows merged by facet, in node order, one row per declaration.
  let mut facetMeta : Std.HashMap String FacetInfo := {}
  let mut facetRows : Std.HashMap String (Std.HashMap Name Json) := {}
  for p in parts do
    for (f, rows) in p.facets do
      facetMeta := facetMeta.insert f.name f
      let mut m := facetRows.getD f.name {}
      for r in rows do
        if let .ok d := r.getObjValAs? String "decl" then
          if !m.contains d.toName then m := m.insert d.toName r
      facetRows := facetRows.insert f.name m
  let facetOrder := ["docstring", "source", "axioms"]
  let names := facetMeta.toArray.map (·.1) |>.qsort fun a b =>
    let ia := facetOrder.idxOf a
    let ib := facetOrder.idxOf b
    ia < ib || (ia == ib && a < b)
  let mut facetEntries : Array Json := #[]
  for name in names do
    let some info := facetMeta.get? name | continue
    let rowsByDecl := facetRows.getD name {}
    let rows := nodes.filterMap (rowsByDecl.get? ·.name)
    let file := s!"facets/{name}.jsonl"
    writeJsonl (cfg.out / file) rows
    facetEntries := facetEntries.push <| Json.mkObj [("name", toJson name),
      ("file", toJson file), ("schema", toJson info.schema), ("count", toJson rows.size),
      ("description", toJson info.description)]

  let metaJson := Json.mkObj [
    ("spec", toJson datasetSpec),
    -- The number of parts the work was split into: besides the code and the extractor's version,
    -- the one thing a dataset can depend on (see the README).
    ("producer", Json.mkObj [("name", toJson "trust-extract"), ("version", toJson extractorVersion),
      ("parts", toJson parts.size)]),
    ("library", Json.mkObj [("root", toJson cfg.root.toString), ("package", toJson project),
      ("repo", toJson cfg.repo), ("commit", toJson commit), ("dirty", toJson dirty),
      ("modules", toJson mods.size),
      ("unavailable", toJson (unavailable.map toString))]),
    ("toolchain", toJson toolchain),
    ("lean", Json.mkObj [("version", toJson Lean.versionString), ("githash", toJson Lean.githash)]),
    ("hasher", Json.mkObj [("name", toJson "semantic_hash"),
      ("revision", toJson semanticHashRevision), ("meaning", toJson "proof-irrelevant"),
      ("content", toJson "proof-relevant"), ("local", toJson localHasherName)]),
    ("counts", Json.mkObj [("nodes", toJson nodes.size), ("project", toJson projectNodes.size),
      ("upstream", toJson upstreamNodes.size)]),
    ("edges", toJson edgeEntries),
    ("facets", toJson facetEntries)]
  IO.FS.writeFile (cfg.out / "meta.json") (metaJson.pretty ++ "\n")
  progress t0 s!"wrote {cfg.out}"

/-! ## Driving the parts -/

/-- The exit code of `extract-part` when importing failed, typically because the process ran out
of memory mappings: the caller splits the part and retries. -/
def importFailedExit : UInt32 := 3

/-- Runs `extract-part` on `mods` in a child process, splitting and retrying on import failure. -/
partial def runPart (cfg : Config) (workDir : System.FilePath) (mods : Array Name) (label : String)
    (t0 : Nat) : IO (Array Part) := do
  let modsFile := workDir / s!"part-{label}.modules"
  let outFile := workDir / s!"part-{label}.json"
  IO.FS.writeFile modsFile ("\n".intercalate (mods.toList.map toString))
  let srcArgs := cfg.srcDirs.foldl (fun a d => a ++ #["--src-dir", d.toString]) #[]
  let args := #["extract-part", "--root", cfg.root.toString, "--modules-file", modsFile.toString,
      "--part-out", outFile.toString] ++ srcArgs ++ (if cfg.axioms then #[] else #["--no-axioms"]) ++
    (if cfg.term then #[] else #["--no-term"])
  progress t0 s!"part {label}: {mods.size} modules"
  let child ← IO.Process.spawn { cmd := (← IO.appPath).toString, args, stdin := .null }
  let code ← child.wait
  if code == 0 then
    let j ← IO.ofExcept (Json.parse (← IO.FS.readFile outFile))
    let part ← IO.ofExcept (Part.ofJson j)
    IO.FS.removeFile outFile
    IO.FS.removeFile modsFile
    return #[part]
  else if code == importFailedExit && mods.size > 1 then
    progress t0 s!"part {label} could not import its modules; splitting it"
    let half := mods.size / 2
    return (← runPart cfg workDir (mods.extract 0 half) s!"{label}a" t0) ++
      (← runPart cfg workDir (mods.extract half mods.size) s!"{label}b" t0)
  else
    throw <| IO.userError s!"part {label} failed (exit {code})"

/-- Extracts the dataset: runs the parts in child processes and merges them. -/
def extract (cfg : Config) : IO Unit := do
  let t0 ← IO.monoMsNow
  let found ← if cfg.modules.isEmpty then discoverModules cfg.srcDirs cfg.root else pure cfg.modules
  if found.isEmpty then
    throw <| IO.userError s!"no modules found under the prefix `{cfg.root}` in {cfg.srcDirs}"
  let unavailable ← if cfg.skip.isEmpty then pure #[] else withImporters cfg.srcDirs found cfg.skip
  if !unavailable.isEmpty then
    progress t0 s!"skipping {unavailable.size} modules: {cfg.skip.size} named, and those importing them"
  let skipped : Std.HashSet Name := unavailable.foldl (·.insert ·) {}
  let mods := found.filter (!skipped.contains ·)
  let project := if cfg.project.isEmpty then cfg.root.toString else cfg.project
  let workDir := cfg.out.withFileName (cfg.out.fileName.getD "dataset" ++ ".parts")
  IO.FS.createDirAll workDir
  let n := max 1 (min cfg.parts mods.size)
  let size := (mods.size + n - 1) / n
  let chunks := (Array.range n).map (fun i => (i, mods.extract (i * size) ((i + 1) * size)))
    |>.filter (!·.2.isEmpty)
  -- Up to `jobs` parts at a time, each in its own child process.
  let mut parts : Array Part := #[]
  let jobs := max 1 cfg.jobs
  for w in [0:(chunks.size + jobs - 1) / jobs] do
    let wave := chunks.extract (w * jobs) ((w + 1) * jobs)
    let tasks ← wave.mapM fun (i, chunk) => IO.asTask (runPart cfg workDir chunk s!"{i}" t0)
    for t in tasks do
      parts := parts ++ (← IO.ofExcept t.get)
  try IO.FS.removeDirAll workDir catch _ => pure ()
  writeDataset cfg parts mods project unavailable t0

/-- The `extract-part` subcommand: collects one part and writes it as JSON. Exits with
`importFailedExit` when importing fails, so that the caller splits the part. -/
def extractPart (cfg : Config) (mods : Array Name) (out : System.FilePath) : IO UInt32 := do
  let t0 ← IO.monoMsNow
  let project := if cfg.project.isEmpty then cfg.root.toString else cfg.project
  let part? ← try
      pure (some (← collectPart cfg mods project t0))
    catch e =>
      if (toString e).startsWith "failed to read file" then
        IO.eprintln s!"import failed: {e}"
        pure none
      else throw e
  match part? with
  | none => return importFailedExit
  | some part =>
    IO.FS.writeFile out part.asJson.compress
    return 0

end TrustExtractor
